version: '3.1'

services:

  discuss:
    image: cscholle/discuss
    restart: always
    build: . 
    ports:
      - 4000:4000
    depends_on: 
      - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  # Adminer is not necessary, but a useful GUI for poking around the postgres db container
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080